name = "sfl-api"
main = "src/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sfl-db"
database_id = "d1968d0f-a984-4fd2-bf4e-c2e0d70f242b"

[[r2_buckets]]
binding = "R2"
bucket_name = "sfl-data"

[vars]
# API_KEY is set via: wrangler secret put API_KEY
